"""empty message

Revision ID: 0329baafc1b8
Revises: e6b463a4d207
Create Date: 2024-06-29 10:24:29.470878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0329baafc1b8'
down_revision = 'e6b463a4d207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(), nullable=True))
        batch_op.drop_column('x_position')
        batch_op.drop_column('y_position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('y_position', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('x_position', sa.INTEGER(), nullable=True))
        batch_op.drop_column('position')

    # ### end Alembic commands ###
