"""empty message

Revision ID: 88d1252ea6b9
Revises: 0329baafc1b8
Create Date: 2024-06-29 11:39:42.264782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d1252ea6b9'
down_revision = '0329baafc1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
