"""creating games table

Revision ID: 8d16d930e58d
Revises: 
Create Date: 2024-06-28 13:17:33.720355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d16d930e58d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_player', sa.String(), nullable=True),
    sa.Column('board', sa.String(), nullable=True),
    sa.Column('player_1', sa.String(), nullable=True),
    sa.Column('player_2', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
