"""empty message

Revision ID: e6b463a4d207
Revises: b0242a4b5bbd
Create Date: 2024-06-29 10:07:08.379009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b463a4d207'
down_revision = 'b0242a4b5bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('board')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
