"""empty message

Revision ID: e9b071c97272
Revises: 8d16d930e58d
Create Date: 2024-06-29 09:17:16.161798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b071c97272'
down_revision = '8d16d930e58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('current_player', sa.VARCHAR(), nullable=True),
    sa.Column('board', sa.VARCHAR(), nullable=True),
    sa.Column('player_1', sa.VARCHAR(), nullable=True),
    sa.Column('player_2', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
